import type { ContentPack, Difficulty } from "@/lib/core/types";

type FlagDefinition = {
  code: string;
  id: string;
  slug: string;
  displayName: string;
  region: "Africa" | "Americas" | "Asia" | "Europe" | "Oceania";
  difficulty: Difficulty;
  aspectRatio: string;
  bands: Array<{ label: string; hex: string }>;
};

// Official SVG assets are sourced from hampusborgos/country-flags (public domain).
// Playable entries use UN member states plus observer states; Taiwan and non-country territories are excluded.
// Each flag intentionally has one safe color target, preferring a large non-white visible SVG field.
// The displayed flag is a memory cue. Scoring uses the declared target color.
function bandKey(label: string) {
  return label.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

const flagDefinitions: FlagDefinition[] = [
  {
    code: "AD",
    id: "andorra",
    slug: "andorra",
    displayName: "Andorra",
    region: "Europe",
    difficulty: "expert",
    aspectRatio: "1000 / 700",
    bands: [
      { label: "red field", hex: "#D0103A" },
    ],
  },
  {
    code: "AE",
    id: "united-arab-emirates",
    slug: "united-arab-emirates",
    displayName: "United Arab Emirates",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "6 / 3",
    bands: [
      { label: "green field", hex: "#00843D" },
    ],
  },
  {
    code: "AF",
    id: "afghanistan",
    slug: "afghanistan",
    displayName: "Afghanistan",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "900 / 600",
    bands: [
      { label: "red field", hex: "#D32011" },
    ],
  },
  {
    code: "AG",
    id: "antigua-and-barbuda",
    slug: "antigua-and-barbuda",
    displayName: "Antigua & Barbuda",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "138 / 92",
    bands: [
      { label: "red field", hex: "#CE1126" },
    ],
  },
  {
    code: "AL",
    id: "albania",
    slug: "albania",
    displayName: "Albania",
    region: "Europe",
    difficulty: "easy",
    aspectRatio: "980 / 700",
    bands: [
      { label: "red field", hex: "#FF0000" },
    ],
  },
  {
    code: "AM",
    id: "armenia",
    slug: "armenia",
    displayName: "Armenia",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "6 / 3",
    bands: [
      { label: "orange field", hex: "#F2A800" },
    ],
  },
  {
    code: "AO",
    id: "angola",
    slug: "angola",
    displayName: "Angola",
    region: "Africa",
    difficulty: "easy",
    aspectRatio: "900 / 600",
    bands: [
      { label: "red field", hex: "#CC092F" },
    ],
  },
  {
    code: "AR",
    id: "argentina",
    slug: "argentina",
    displayName: "Argentina",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "800 / 500",
    bands: [
      { label: "blue field", hex: "#74ACDF" },
    ],
  },
  {
    code: "AT",
    id: "austria",
    slug: "austria",
    displayName: "Austria",
    region: "Europe",
    difficulty: "easy",
    aspectRatio: "9 / 6",
    bands: [
      { label: "red field", hex: "#ED2939" },
    ],
  },
  {
    code: "AU",
    id: "australia",
    slug: "australia",
    displayName: "Australia",
    region: "Oceania",
    difficulty: "normal",
    aspectRatio: "10080 / 5040",
    bands: [
      { label: "blue field", hex: "#012169" },
    ],
  },
  {
    code: "AZ",
    id: "azerbaijan",
    slug: "azerbaijan",
    displayName: "Azerbaijan",
    region: "Asia",
    difficulty: "expert",
    aspectRatio: "1200 / 600",
    bands: [
      { label: "green field", hex: "#3F9C35" },
    ],
  },
  {
    code: "BA",
    id: "bosnia-and-herzegovina",
    slug: "bosnia-and-herzegovina",
    displayName: "Bosnia & Herzegovina",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "16 / 8",
    bands: [
      { label: "blue field", hex: "#002395" },
    ],
  },
  {
    code: "BB",
    id: "barbados",
    slug: "barbados",
    displayName: "Barbados",
    region: "Americas",
    difficulty: "normal",
    aspectRatio: "24000 / 16000",
    bands: [
      { label: "blue field", hex: "#00267F" },
    ],
  },
  {
    code: "BD",
    id: "bangladesh",
    slug: "bangladesh",
    displayName: "Bangladesh",
    region: "Asia",
    difficulty: "easy",
    aspectRatio: "20 / 12",
    bands: [
      { label: "green field", hex: "#006A4E" },
    ],
  },
  {
    code: "BE",
    id: "belgium",
    slug: "belgium",
    displayName: "Belgium",
    region: "Europe",
    difficulty: "easy",
    aspectRatio: "45 / 39",
    bands: [
      { label: "red field", hex: "#ED2939" },
    ],
  },
  {
    code: "BF",
    id: "burkina-faso",
    slug: "burkina-faso",
    displayName: "Burkina Faso",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "900 / 600",
    bands: [
      { label: "green field", hex: "#009E49" },
    ],
  },
  {
    code: "BG",
    id: "bulgaria",
    slug: "bulgaria",
    displayName: "Bulgaria",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "5 / 3",
    bands: [
      { label: "green field", hex: "#00966E" },
    ],
  },
  {
    code: "BH",
    id: "bahrain",
    slug: "bahrain",
    displayName: "Bahrain",
    region: "Asia",
    difficulty: "easy",
    aspectRatio: "1500 / 900",
    bands: [
      { label: "red field", hex: "#CE1126" },
    ],
  },
  {
    code: "BI",
    id: "burundi",
    slug: "burundi",
    displayName: "Burundi",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "500 / 300",
    bands: [
      { label: "red field", hex: "#CE1126" },
    ],
  },
  {
    code: "BJ",
    id: "benin",
    slug: "benin",
    displayName: "Benin",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "3 / 2",
    bands: [
      { label: "red field", hex: "#E8112D" },
    ],
  },
  {
    code: "BN",
    id: "brunei",
    slug: "brunei",
    displayName: "Brunei",
    region: "Asia",
    difficulty: "expert",
    aspectRatio: "1440 / 720",
    bands: [
      { label: "yellow field", hex: "#F7E017" },
    ],
  },
  {
    code: "BO",
    id: "bolivia",
    slug: "bolivia",
    displayName: "Bolivia",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "291.042 / 198.438",
    bands: [
      { label: "green field", hex: "#00702D" },
    ],
  },
  {
    code: "BR",
    id: "brazil",
    slug: "brazil",
    displayName: "Brazil",
    region: "Americas",
    difficulty: "normal",
    aspectRatio: "4200 / 2940",
    bands: [
      { label: "green field", hex: "#009B3A" },
    ],
  },
  {
    code: "BS",
    id: "bahamas",
    slug: "bahamas",
    displayName: "Bahamas",
    region: "Americas",
    difficulty: "easy",
    aspectRatio: "6 / 3",
    bands: [
      { label: "cyan field", hex: "#00778B" },
    ],
  },
  {
    code: "BT",
    id: "bhutan",
    slug: "bhutan",
    displayName: "Bhutan",
    region: "Asia",
    difficulty: "expert",
    aspectRatio: "900 / 600",
    bands: [
      { label: "orange field", hex: "#FF4E12" },
    ],
  },
  {
    code: "BW",
    id: "botswana",
    slug: "botswana",
    displayName: "Botswana",
    region: "Africa",
    difficulty: "easy",
    aspectRatio: "36 / 24",
    bands: [
      { label: "blue field", hex: "#6DA9D2" },
    ],
  },
  {
    code: "BY",
    id: "belarus",
    slug: "belarus",
    displayName: "Belarus",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "900 / 450",
    bands: [
      { label: "red field", hex: "#D22730" },
    ],
  },
  {
    code: "BZ",
    id: "belize",
    slug: "belize",
    displayName: "Belize",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "1000 / 600",
    bands: [
      { label: "red field", hex: "#D90F19" },
    ],
  },
  {
    code: "CA",
    id: "canada",
    slug: "canada",
    displayName: "Canada",
    region: "Americas",
    difficulty: "easy",
    aspectRatio: "9600 / 4800",
    bands: [
      { label: "red field", hex: "#D52B1E" },
    ],
  },
  {
    code: "CD",
    id: "democratic-republic-of-the-congo",
    slug: "democratic-republic-of-the-congo",
    displayName: "Democratic Republic of the Congo",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "800 / 600",
    bands: [
      { label: "blue field", hex: "#007FFF" },
    ],
  },
  {
    code: "CF",
    id: "central-african-republic",
    slug: "central-african-republic",
    displayName: "Central African Republic",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "12 / 8",
    bands: [
      { label: "red field", hex: "#D21034" },
    ],
  },
  {
    code: "CG",
    id: "republic-of-the-congo",
    slug: "republic-of-the-congo",
    displayName: "Republic of the Congo",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "3 / 2",
    bands: [
      { label: "green field", hex: "#009543" },
    ],
  },
  {
    code: "CH",
    id: "switzerland",
    slug: "switzerland",
    displayName: "Switzerland",
    region: "Europe",
    difficulty: "easy",
    aspectRatio: "32 / 32",
    bands: [
      { label: "red field", hex: "#DA291C" },
    ],
  },
  {
    code: "CI",
    id: "ivory-coast",
    slug: "ivory-coast",
    displayName: "Ivory Coast",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "3 / 2",
    bands: [
      { label: "green field", hex: "#009E60" },
    ],
  },
  {
    code: "CL",
    id: "chile",
    slug: "chile",
    displayName: "Chile",
    region: "Americas",
    difficulty: "normal",
    aspectRatio: "24 / 16",
    bands: [
      { label: "red field", hex: "#D52B1E" },
    ],
  },
  {
    code: "CM",
    id: "cameroon",
    slug: "cameroon",
    displayName: "Cameroon",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "90 / 60",
    bands: [
      { label: "cyan field", hex: "#007A5E" },
    ],
  },
  {
    code: "CN",
    id: "china",
    slug: "china",
    displayName: "China",
    region: "Asia",
    difficulty: "easy",
    aspectRatio: "30 / 20",
    bands: [
      { label: "red field", hex: "#EE1C25" },
    ],
  },
  {
    code: "CO",
    id: "colombia",
    slug: "colombia",
    displayName: "Colombia",
    region: "Americas",
    difficulty: "normal",
    aspectRatio: "6 / 4",
    bands: [
      { label: "red field", hex: "#CE1126" },
    ],
  },
  {
    code: "CR",
    id: "costa-rica",
    slug: "costa-rica",
    displayName: "Costa Rica",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "1000 / 600",
    bands: [
      { label: "blue field", hex: "#002B7F" },
    ],
  },
  {
    code: "CU",
    id: "cuba",
    slug: "cuba",
    displayName: "Cuba",
    region: "Americas",
    difficulty: "normal",
    aspectRatio: "800 / 400",
    bands: [
      { label: "blue field", hex: "#002A8F" },
    ],
  },
  {
    code: "CV",
    id: "cape-verde",
    slug: "cape-verde",
    displayName: "Cape Verde",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "510 / 300",
    bands: [
      { label: "blue field", hex: "#003893" },
    ],
  },
  {
    code: "CY",
    id: "cyprus",
    slug: "cyprus",
    displayName: "Cyprus",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "900 / 600",
    bands: [
      { label: "orange field", hex: "#D57800" },
    ],
  },
  {
    code: "CZ",
    id: "czechia",
    slug: "czechia",
    displayName: "Czechia",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "900 / 600",
    bands: [
      { label: "red field", hex: "#D7141A" },
    ],
  },
  {
    code: "DE",
    id: "germany",
    slug: "germany",
    displayName: "Germany",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "5 / 3",
    bands: [
      { label: "red field", hex: "#DD0000" },
    ],
  },
  {
    code: "DJ",
    id: "djibouti",
    slug: "djibouti",
    displayName: "Djibouti",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "15 / 10",
    bands: [
      { label: "blue field", hex: "#6AB2E7" },
    ],
  },
  {
    code: "DK",
    id: "denmark",
    slug: "denmark",
    displayName: "Denmark",
    region: "Europe",
    difficulty: "easy",
    aspectRatio: "370 / 280",
    bands: [
      { label: "red field", hex: "#C60C30" },
    ],
  },
  {
    code: "DM",
    id: "dominica",
    slug: "dominica",
    displayName: "Dominica",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "1200 / 600",
    bands: [
      { label: "green field", hex: "#006B3F" },
    ],
  },
  {
    code: "DO",
    id: "dominican-republic",
    slug: "dominican-republic",
    displayName: "Dominican Republic",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "900 / 600",
    bands: [
      { label: "blue field", hex: "#002D62" },
    ],
  },
  {
    code: "DZ",
    id: "algeria",
    slug: "algeria",
    displayName: "Algeria",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "900 / 600",
    bands: [
      { label: "green field", hex: "#006233" },
    ],
  },
  {
    code: "EC",
    id: "ecuador",
    slug: "ecuador",
    displayName: "Ecuador",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "1440 / 960",
    bands: [
      { label: "red field", hex: "#ED1C24" },
    ],
  },
  {
    code: "EE",
    id: "estonia",
    slug: "estonia",
    displayName: "Estonia",
    region: "Europe",
    difficulty: "easy",
    aspectRatio: "33 / 21",
    bands: [
      { label: "blue field", hex: "#0072CE" },
    ],
  },
  {
    code: "EG",
    id: "egypt",
    slug: "egypt",
    displayName: "Egypt",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "900 / 600",
    bands: [
      { label: "red field", hex: "#CE1126" },
    ],
  },
  {
    code: "ER",
    id: "eritrea",
    slug: "eritrea",
    displayName: "Eritrea",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "14400 / 7200",
    bands: [
      { label: "red field", hex: "#E4002B" },
    ],
  },
  {
    code: "ES",
    id: "spain",
    slug: "spain",
    displayName: "Spain",
    region: "Europe",
    difficulty: "expert",
    aspectRatio: "750 / 500",
    bands: [
      { label: "red field", hex: "#C60B1E" },
    ],
  },
  {
    code: "ET",
    id: "ethiopia",
    slug: "ethiopia",
    displayName: "Ethiopia",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "720 / 360",
    bands: [
      { label: "red field", hex: "#DA121A" },
    ],
  },
  {
    code: "FI",
    id: "finland",
    slug: "finland",
    displayName: "Finland",
    region: "Europe",
    difficulty: "easy",
    aspectRatio: "1800 / 1100",
    bands: [
      { label: "blue field", hex: "#003580" },
    ],
  },
  {
    code: "FJ",
    id: "fiji",
    slug: "fiji",
    displayName: "Fiji",
    region: "Oceania",
    difficulty: "expert",
    aspectRatio: "1200 / 600",
    bands: [
      { label: "blue field", hex: "#012169" },
    ],
  },
  {
    code: "FM",
    id: "micronesia",
    slug: "micronesia",
    displayName: "Micronesia",
    region: "Oceania",
    difficulty: "easy",
    aspectRatio: "38 / 20",
    bands: [
      { label: "blue field", hex: "#75B2DD" },
    ],
  },
  {
    code: "FR",
    id: "france",
    slug: "france",
    displayName: "France",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "3 / 2",
    bands: [
      { label: "red field", hex: "#EC1920" },
    ],
  },
  {
    code: "GA",
    id: "gabon",
    slug: "gabon",
    displayName: "Gabon",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "400 / 300",
    bands: [
      { label: "blue field", hex: "#3A75C4" },
    ],
  },
  {
    code: "GB",
    id: "united-kingdom",
    slug: "united-kingdom",
    displayName: "United Kingdom",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "60 / 30",
    bands: [
      { label: "blue field", hex: "#012169" },
    ],
  },
  {
    code: "GD",
    id: "grenada",
    slug: "grenada",
    displayName: "Grenada",
    region: "Americas",
    difficulty: "normal",
    aspectRatio: "500 / 300",
    bands: [
      { label: "red field", hex: "#CE1126" },
    ],
  },
  {
    code: "GE",
    id: "georgia",
    slug: "georgia",
    displayName: "Georgia",
    region: "Asia",
    difficulty: "easy",
    aspectRatio: "300 / 200",
    bands: [
      { label: "red field", hex: "#FF0000" },
    ],
  },
  {
    code: "GH",
    id: "ghana",
    slug: "ghana",
    displayName: "Ghana",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "450 / 300",
    bands: [
      { label: "green field", hex: "#006B3F" },
    ],
  },
  {
    code: "GM",
    id: "gambia",
    slug: "gambia",
    displayName: "Gambia",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "27 / 18",
    bands: [
      { label: "green field", hex: "#3A7728" },
    ],
  },
  {
    code: "GN",
    id: "guinea",
    slug: "guinea",
    displayName: "Guinea",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "3 / 2",
    bands: [
      { label: "red field", hex: "#CE1126" },
    ],
  },
  {
    code: "GQ",
    id: "equatorial-guinea",
    slug: "equatorial-guinea",
    displayName: "Equatorial Guinea",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "3600 / 2400",
    bands: [
      { label: "red field", hex: "#E32118" },
    ],
  },
  {
    code: "GR",
    id: "greece",
    slug: "greece",
    displayName: "Greece",
    region: "Europe",
    difficulty: "easy",
    aspectRatio: "27 / 18",
    bands: [
      { label: "blue field", hex: "#0D5EAF" },
    ],
  },
  {
    code: "GT",
    id: "guatemala",
    slug: "guatemala",
    displayName: "Guatemala",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "960 / 600",
    bands: [
      { label: "blue field", hex: "#4997D0" },
    ],
  },
  {
    code: "GW",
    id: "guinea-bissau",
    slug: "guinea-bissau",
    displayName: "Guinea-Bissau",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "12 / 6",
    bands: [
      { label: "green field", hex: "#009E49" },
    ],
  },
  {
    code: "GY",
    id: "guyana",
    slug: "guyana",
    displayName: "Guyana",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "500 / 300",
    bands: [
      { label: "green field", hex: "#009E49" },
    ],
  },
  {
    code: "HN",
    id: "honduras",
    slug: "honduras",
    displayName: "Honduras",
    region: "Americas",
    difficulty: "easy",
    aspectRatio: "1260 / 630",
    bands: [
      { label: "blue field", hex: "#0D3B99" },
    ],
  },
  {
    code: "HR",
    id: "croatia",
    slug: "croatia",
    displayName: "Croatia",
    region: "Europe",
    difficulty: "expert",
    aspectRatio: "1200 / 600",
    bands: [
      { label: "blue field", hex: "#001489" },
    ],
  },
  {
    code: "HT",
    id: "haiti",
    slug: "haiti",
    displayName: "Haiti",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "1000 / 600",
    bands: [
      { label: "red field", hex: "#D21034" },
    ],
  },
  {
    code: "HU",
    id: "hungary",
    slug: "hungary",
    displayName: "Hungary",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "6 / 3",
    bands: [
      { label: "green field", hex: "#477050" },
    ],
  },
  {
    code: "ID",
    id: "indonesia",
    slug: "indonesia",
    displayName: "Indonesia",
    region: "Asia",
    difficulty: "easy",
    aspectRatio: "3 / 2",
    bands: [
      { label: "red field", hex: "#FF0000" },
    ],
  },
  {
    code: "IE",
    id: "ireland",
    slug: "ireland",
    displayName: "Ireland",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "6 / 3",
    bands: [
      { label: "green field", hex: "#009A44" },
    ],
  },
  {
    code: "IL",
    id: "israel",
    slug: "israel",
    displayName: "Israel",
    region: "Asia",
    difficulty: "easy",
    aspectRatio: "1100 / 800",
    bands: [
      { label: "blue field", hex: "#0038B8" },
    ],
  },
  {
    code: "IN",
    id: "india",
    slug: "india",
    displayName: "India",
    region: "Asia",
    difficulty: "expert",
    aspectRatio: "900 / 600",
    bands: [
      { label: "green field", hex: "#128807" },
    ],
  },
  {
    code: "IQ",
    id: "iraq",
    slug: "iraq",
    displayName: "Iraq",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "900 / 600",
    bands: [
      { label: "red field", hex: "#CE1126" },
    ],
  },
  {
    code: "IR",
    id: "iran",
    slug: "iran",
    displayName: "Iran",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "630 / 360",
    bands: [
      { label: "red field", hex: "#DA0000" },
    ],
  },
  {
    code: "IS",
    id: "iceland",
    slug: "iceland",
    displayName: "Iceland",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "25 / 18",
    bands: [
      { label: "blue field", hex: "#003087" },
    ],
  },
  {
    code: "IT",
    id: "italy",
    slug: "italy",
    displayName: "Italy",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "3 / 2",
    bands: [
      { label: "green field", hex: "#008C45" },
    ],
  },
  {
    code: "JM",
    id: "jamaica",
    slug: "jamaica",
    displayName: "Jamaica",
    region: "Americas",
    difficulty: "normal",
    aspectRatio: "12 / 6",
    bands: [
      { label: "green field", hex: "#007749" },
    ],
  },
  {
    code: "JO",
    id: "jordan",
    slug: "jordan",
    displayName: "Jordan",
    region: "Asia",
    difficulty: "expert",
    aspectRatio: "840 / 420",
    bands: [
      { label: "green field", hex: "#007A3D" },
    ],
  },
  {
    code: "JP",
    id: "japan",
    slug: "japan",
    displayName: "Japan",
    region: "Asia",
    difficulty: "easy",
    aspectRatio: "900 / 600",
    bands: [
      { label: "red field", hex: "#BC002D" },
    ],
  },
  {
    code: "KE",
    id: "kenya",
    slug: "kenya",
    displayName: "Kenya",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "240 / 160",
    bands: [
      { label: "green field", hex: "#006600" },
    ],
  },
  {
    code: "KG",
    id: "kyrgyzstan",
    slug: "kyrgyzstan",
    displayName: "Kyrgyzstan",
    region: "Asia",
    difficulty: "easy",
    aspectRatio: "1000 / 600",
    bands: [
      { label: "red field", hex: "#EE2737" },
    ],
  },
  {
    code: "KH",
    id: "cambodia",
    slug: "cambodia",
    displayName: "Cambodia",
    region: "Asia",
    difficulty: "expert",
    aspectRatio: "625 / 400",
    bands: [
      { label: "blue field", hex: "#032EA1" },
    ],
  },
  {
    code: "KI",
    id: "kiribati",
    slug: "kiribati",
    displayName: "Kiribati",
    region: "Oceania",
    difficulty: "expert",
    aspectRatio: "600 / 300",
    bands: [
      { label: "red field", hex: "#C81010" },
    ],
  },
  {
    code: "KM",
    id: "comoros",
    slug: "comoros",
    displayName: "Comoros",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "500 / 300",
    bands: [
      { label: "blue field", hex: "#3A75C4" },
    ],
  },
  {
    code: "KN",
    id: "st-kitts-and-nevis",
    slug: "st-kitts-and-nevis",
    displayName: "St. Kitts & Nevis",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "750 / 500",
    bands: [
      { label: "green field", hex: "#009E49" },
    ],
  },
  {
    code: "KP",
    id: "north-korea",
    slug: "north-korea",
    displayName: "North Korea",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "72 / 36",
    bands: [
      { label: "blue field", hex: "#024FA2" },
    ],
  },
  {
    code: "KR",
    id: "south-korea",
    slug: "south-korea",
    displayName: "South Korea",
    region: "Asia",
    difficulty: "expert",
    aspectRatio: "72 / 48",
    bands: [
      { label: "red field", hex: "#CD2E3A" },
    ],
  },
  {
    code: "KW",
    id: "kuwait",
    slug: "kuwait",
    displayName: "Kuwait",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "12 / 6",
    bands: [
      { label: "green field", hex: "#007A3D" },
    ],
  },
  {
    code: "KZ",
    id: "kazakhstan",
    slug: "kazakhstan",
    displayName: "Kazakhstan",
    region: "Asia",
    difficulty: "easy",
    aspectRatio: "2000 / 1000",
    bands: [
      { label: "cyan field", hex: "#00AFCA" },
    ],
  },
  {
    code: "LA",
    id: "laos",
    slug: "laos",
    displayName: "Laos",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "6 / 4",
    bands: [
      { label: "red field", hex: "#CE1126" },
    ],
  },
  {
    code: "LB",
    id: "lebanon",
    slug: "lebanon",
    displayName: "Lebanon",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "750 / 500",
    bands: [
      { label: "red field", hex: "#ED1C24" },
    ],
  },
  {
    code: "LC",
    id: "st-lucia",
    slug: "st-lucia",
    displayName: "St. Lucia",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "600 / 300",
    bands: [
      { label: "blue field", hex: "#66CCFF" },
    ],
  },
  {
    code: "LI",
    id: "liechtenstein",
    slug: "liechtenstein",
    displayName: "Liechtenstein",
    region: "Europe",
    difficulty: "expert",
    aspectRatio: "1000 / 600",
    bands: [
      { label: "blue field", hex: "#002B7F" },
    ],
  },
  {
    code: "LK",
    id: "sri-lanka",
    slug: "sri-lanka",
    displayName: "Sri Lanka",
    region: "Asia",
    difficulty: "expert",
    aspectRatio: "1200 / 600",
    bands: [
      { label: "orange field", hex: "#FFBE29" },
    ],
  },
  {
    code: "LR",
    id: "liberia",
    slug: "liberia",
    displayName: "Liberia",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "209 / 110",
    bands: [
      { label: "red field", hex: "#BF0A30" },
    ],
  },
  {
    code: "LS",
    id: "lesotho",
    slug: "lesotho",
    displayName: "Lesotho",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "450 / 300",
    bands: [
      { label: "green field", hex: "#009543" },
    ],
  },
  {
    code: "LT",
    id: "lithuania",
    slug: "lithuania",
    displayName: "Lithuania",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "5 / 3",
    bands: [
      { label: "red field", hex: "#BE3A34" },
    ],
  },
  {
    code: "LU",
    id: "luxembourg",
    slug: "luxembourg",
    displayName: "Luxembourg",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "10 / 6",
    bands: [
      { label: "blue field", hex: "#00A3E0" },
    ],
  },
  {
    code: "LV",
    id: "latvia",
    slug: "latvia",
    displayName: "Latvia",
    region: "Europe",
    difficulty: "easy",
    aspectRatio: "6 / 3",
    bands: [
      { label: "red field", hex: "#9D2235" },
    ],
  },
  {
    code: "LY",
    id: "libya",
    slug: "libya",
    displayName: "Libya",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "960 / 480",
    bands: [
      { label: "green field", hex: "#239E46" },
    ],
  },
  {
    code: "MA",
    id: "morocco",
    slug: "morocco",
    displayName: "Morocco",
    region: "Africa",
    difficulty: "easy",
    aspectRatio: "9 / 6",
    bands: [
      { label: "red field", hex: "#B7312C" },
    ],
  },
  {
    code: "MC",
    id: "monaco",
    slug: "monaco",
    displayName: "Monaco",
    region: "Europe",
    difficulty: "easy",
    aspectRatio: "5 / 4",
    bands: [
      { label: "red field", hex: "#CE1126" },
    ],
  },
  {
    code: "MD",
    id: "moldova",
    slug: "moldova",
    displayName: "Moldova",
    region: "Europe",
    difficulty: "expert",
    aspectRatio: "1800 / 900",
    bands: [
      { label: "red field", hex: "#C8102E" },
    ],
  },
  {
    code: "ME",
    id: "montenegro",
    slug: "montenegro",
    displayName: "Montenegro",
    region: "Europe",
    difficulty: "expert",
    aspectRatio: "640 / 320",
    bands: [
      { label: "yellow field", hex: "#D3AE3B" },
    ],
  },
  {
    code: "MG",
    id: "madagascar",
    slug: "madagascar",
    displayName: "Madagascar",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "3 / 2",
    bands: [
      { label: "green field", hex: "#007E3A" },
    ],
  },
  {
    code: "MH",
    id: "marshall-islands",
    slug: "marshall-islands",
    displayName: "Marshall Islands",
    region: "Oceania",
    difficulty: "normal",
    aspectRatio: "57 / 30",
    bands: [
      { label: "blue field", hex: "#003087" },
    ],
  },
  {
    code: "MK",
    id: "north-macedonia",
    slug: "north-macedonia",
    displayName: "North Macedonia",
    region: "Europe",
    difficulty: "easy",
    aspectRatio: "280 / 140",
    bands: [
      { label: "red field", hex: "#D82126" },
    ],
  },
  {
    code: "ML",
    id: "mali",
    slug: "mali",
    displayName: "Mali",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "450 / 300",
    bands: [
      { label: "red field", hex: "#CE1126" },
    ],
  },
  {
    code: "MM",
    id: "myanmar-burma",
    slug: "myanmar-burma",
    displayName: "Myanmar (Burma)",
    region: "Asia",
    difficulty: "expert",
    aspectRatio: "18 / 12",
    bands: [
      { label: "yellow field", hex: "#FECB00" },
    ],
  },
  {
    code: "MN",
    id: "mongolia",
    slug: "mongolia",
    displayName: "Mongolia",
    region: "Asia",
    difficulty: "expert",
    aspectRatio: "1200 / 600",
    bands: [
      { label: "red field", hex: "#DA2032" },
    ],
  },
  {
    code: "MR",
    id: "mauritania",
    slug: "mauritania",
    displayName: "Mauritania",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "3000 / 2000",
    bands: [
      { label: "red field", hex: "#D01C1F" },
    ],
  },
  {
    code: "MT",
    id: "malta",
    slug: "malta",
    displayName: "Malta",
    region: "Europe",
    difficulty: "expert",
    aspectRatio: "900 / 600",
    bands: [
      { label: "red field", hex: "#C8102E" },
    ],
  },
  {
    code: "MU",
    id: "mauritius",
    slug: "mauritius",
    displayName: "Mauritius",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "6 / 4",
    bands: [
      { label: "green field", hex: "#00A551" },
    ],
  },
  {
    code: "MV",
    id: "maldives",
    slug: "maldives",
    displayName: "Maldives",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "720 / 480",
    bands: [
      { label: "red field", hex: "#D21034" },
    ],
  },
  {
    code: "MW",
    id: "malawi",
    slug: "malawi",
    displayName: "Malawi",
    region: "Africa",
    difficulty: "easy",
    aspectRatio: "450 / 300",
    bands: [
      { label: "green field", hex: "#339E35" },
    ],
  },
  {
    code: "MX",
    id: "mexico",
    slug: "mexico",
    displayName: "Mexico",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "980 / 560",
    bands: [
      { label: "red field", hex: "#CE1126" },
    ],
  },
  {
    code: "MY",
    id: "malaysia",
    slug: "malaysia",
    displayName: "Malaysia",
    region: "Asia",
    difficulty: "expert",
    aspectRatio: "13440 / 6720",
    bands: [
      { label: "blue field", hex: "#000066" },
    ],
  },
  {
    code: "MZ",
    id: "mozambique",
    slug: "mozambique",
    displayName: "Mozambique",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "900 / 600",
    bands: [
      { label: "red field", hex: "#D21034" },
    ],
  },
  {
    code: "NA",
    id: "namibia",
    slug: "namibia",
    displayName: "Namibia",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "90 / 60",
    bands: [
      { label: "blue field", hex: "#003580" },
    ],
  },
  {
    code: "NE",
    id: "niger",
    slug: "niger",
    displayName: "Niger",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "700 / 600",
    bands: [
      { label: "green field", hex: "#0DB02B" },
    ],
  },
  {
    code: "NG",
    id: "nigeria",
    slug: "nigeria",
    displayName: "Nigeria",
    region: "Africa",
    difficulty: "easy",
    aspectRatio: "6 / 3",
    bands: [
      { label: "green field", hex: "#008751" },
    ],
  },
  {
    code: "NI",
    id: "nicaragua",
    slug: "nicaragua",
    displayName: "Nicaragua",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "1000 / 600",
    bands: [
      { label: "blue field", hex: "#0067C6" },
    ],
  },
  {
    code: "NL",
    id: "netherlands",
    slug: "netherlands",
    displayName: "Netherlands",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "9 / 6",
    bands: [
      { label: "blue field", hex: "#21468B" },
    ],
  },
  {
    code: "NO",
    id: "norway",
    slug: "norway",
    displayName: "Norway",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "22 / 16",
    bands: [
      { label: "red field", hex: "#BA0C2F" },
    ],
  },
  {
    code: "NP",
    id: "nepal",
    slug: "nepal",
    displayName: "Nepal",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "71.571 / 87.246",
    bands: [
      { label: "red field", hex: "#DC143C" },
    ],
  },
  {
    code: "NR",
    id: "nauru",
    slug: "nauru",
    displayName: "Nauru",
    region: "Oceania",
    difficulty: "normal",
    aspectRatio: "600 / 300",
    bands: [
      { label: "blue field", hex: "#002B7F" },
    ],
  },
  {
    code: "NZ",
    id: "new-zealand",
    slug: "new-zealand",
    displayName: "New Zealand",
    region: "Oceania",
    difficulty: "normal",
    aspectRatio: "1200 / 600",
    bands: [
      { label: "blue field", hex: "#012169" },
    ],
  },
  {
    code: "OM",
    id: "oman",
    slug: "oman",
    displayName: "Oman",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "1200 / 600",
    bands: [
      { label: "red field", hex: "#DB161B" },
    ],
  },
  {
    code: "PA",
    id: "panama",
    slug: "panama",
    displayName: "Panama",
    region: "Americas",
    difficulty: "normal",
    aspectRatio: "900 / 600",
    bands: [
      { label: "blue field", hex: "#002855" },
    ],
  },
  {
    code: "PE",
    id: "peru",
    slug: "peru",
    displayName: "Peru",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "900 / 600",
    bands: [
      { label: "red field", hex: "#D91023" },
    ],
  },
  {
    code: "PG",
    id: "papua-new-guinea",
    slug: "papua-new-guinea",
    displayName: "Papua New Guinea",
    region: "Oceania",
    difficulty: "expert",
    aspectRatio: "768 / 576",
    bands: [
      { label: "red field", hex: "#CE1126" },
    ],
  },
  {
    code: "PH",
    id: "philippines",
    slug: "philippines",
    displayName: "Philippines",
    region: "Asia",
    difficulty: "expert",
    aspectRatio: "180 / 90",
    bands: [
      { label: "blue field", hex: "#0038A8" },
    ],
  },
  {
    code: "PK",
    id: "pakistan",
    slug: "pakistan",
    displayName: "Pakistan",
    region: "Asia",
    difficulty: "easy",
    aspectRatio: "120 / 80",
    bands: [
      { label: "green field", hex: "#01411C" },
    ],
  },
  {
    code: "PL",
    id: "poland",
    slug: "poland",
    displayName: "Poland",
    region: "Europe",
    difficulty: "easy",
    aspectRatio: "16 / 10",
    bands: [
      { label: "red field", hex: "#DC143C" },
    ],
  },
  {
    code: "PS",
    id: "palestine",
    slug: "palestine",
    displayName: "Palestine",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "6 / 3",
    bands: [
      { label: "green field", hex: "#007A3D" },
    ],
  },
  {
    code: "PT",
    id: "portugal",
    slug: "portugal",
    displayName: "Portugal",
    region: "Europe",
    difficulty: "expert",
    aspectRatio: "600 / 400",
    bands: [
      { label: "red field", hex: "#FF0000" },
    ],
  },
  {
    code: "PW",
    id: "palau",
    slug: "palau",
    displayName: "Palau",
    region: "Oceania",
    difficulty: "easy",
    aspectRatio: "16 / 10",
    bands: [
      { label: "blue field", hex: "#0099FF" },
    ],
  },
  {
    code: "PY",
    id: "paraguay",
    slug: "paraguay",
    displayName: "Paraguay",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "1200 / 660",
    bands: [
      { label: "blue field", hex: "#0038A8" },
    ],
  },
  {
    code: "QA",
    id: "qatar",
    slug: "qatar",
    displayName: "Qatar",
    region: "Asia",
    difficulty: "easy",
    aspectRatio: "1400 / 550",
    bands: [
      { label: "red field", hex: "#8D1B3D" },
    ],
  },
  {
    code: "RO",
    id: "romania",
    slug: "romania",
    displayName: "Romania",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "3 / 2",
    bands: [
      { label: "blue field", hex: "#002B7F" },
    ],
  },
  {
    code: "RS",
    id: "serbia",
    slug: "serbia",
    displayName: "Serbia",
    region: "Europe",
    difficulty: "expert",
    aspectRatio: "756.13 / 504.09",
    bands: [
      { label: "red field", hex: "#E40046" },
    ],
  },
  {
    code: "RU",
    id: "russia",
    slug: "russia",
    displayName: "Russia",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "9 / 6",
    bands: [
      { label: "red field", hex: "#DA291C" },
    ],
  },
  {
    code: "RW",
    id: "rwanda",
    slug: "rwanda",
    displayName: "Rwanda",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "1080 / 720",
    bands: [
      { label: "green field", hex: "#20603D" },
    ],
  },
  {
    code: "SA",
    id: "saudi-arabia",
    slug: "saudi-arabia",
    displayName: "Saudi Arabia",
    region: "Asia",
    difficulty: "easy",
    aspectRatio: "900 / 600",
    bands: [
      { label: "green field", hex: "#006C35" },
    ],
  },
  {
    code: "SB",
    id: "solomon-islands",
    slug: "solomon-islands",
    displayName: "Solomon Islands",
    region: "Oceania",
    difficulty: "expert",
    aspectRatio: "800 / 400",
    bands: [
      { label: "blue field", hex: "#0051BA" },
    ],
  },
  {
    code: "SC",
    id: "seychelles",
    slug: "seychelles",
    displayName: "Seychelles",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "900 / 450",
    bands: [
      { label: "red field", hex: "#D62828" },
    ],
  },
  {
    code: "SD",
    id: "sudan",
    slug: "sudan",
    displayName: "Sudan",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "12 / 6",
    bands: [
      { label: "red field", hex: "#D21034" },
    ],
  },
  {
    code: "SE",
    id: "sweden",
    slug: "sweden",
    displayName: "Sweden",
    region: "Europe",
    difficulty: "easy",
    aspectRatio: "16 / 10",
    bands: [
      { label: "blue field", hex: "#006AA7" },
    ],
  },
  {
    code: "SG",
    id: "singapore",
    slug: "singapore",
    displayName: "Singapore",
    region: "Asia",
    difficulty: "easy",
    aspectRatio: "4320 / 2880",
    bands: [
      { label: "red field", hex: "#ED2939" },
    ],
  },
  {
    code: "SI",
    id: "slovenia",
    slug: "slovenia",
    displayName: "Slovenia",
    region: "Europe",
    difficulty: "expert",
    aspectRatio: "12 / 6",
    bands: [
      { label: "red field", hex: "#FF0000" },
    ],
  },
  {
    code: "SK",
    id: "slovakia",
    slug: "slovakia",
    displayName: "Slovakia",
    region: "Europe",
    difficulty: "normal",
    aspectRatio: "900 / 600",
    bands: [
      { label: "red field", hex: "#EE1C25" },
    ],
  },
  {
    code: "SL",
    id: "sierra-leone",
    slug: "sierra-leone",
    displayName: "Sierra Leone",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "9 / 6",
    bands: [
      { label: "blue field", hex: "#0072C6" },
    ],
  },
  {
    code: "SM",
    id: "san-marino",
    slug: "san-marino",
    displayName: "San Marino",
    region: "Europe",
    difficulty: "expert",
    aspectRatio: "800 / 600",
    bands: [
      { label: "blue field", hex: "#62B5E5" },
    ],
  },
  {
    code: "SN",
    id: "senegal",
    slug: "senegal",
    displayName: "Senegal",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "900 / 600",
    bands: [
      { label: "green field", hex: "#00853F" },
    ],
  },
  {
    code: "SO",
    id: "somalia",
    slug: "somalia",
    displayName: "Somalia",
    region: "Africa",
    difficulty: "easy",
    aspectRatio: "81 / 54",
    bands: [
      { label: "blue field", hex: "#4189DD" },
    ],
  },
  {
    code: "SR",
    id: "suriname",
    slug: "suriname",
    displayName: "Suriname",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "900 / 600",
    bands: [
      { label: "green field", hex: "#007A33" },
    ],
  },
  {
    code: "SS",
    id: "south-sudan",
    slug: "south-sudan",
    displayName: "South Sudan",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "20 / 10",
    bands: [
      { label: "green field", hex: "#078930" },
    ],
  },
  {
    code: "ST",
    id: "sao-tome-and-principe",
    slug: "sao-tome-and-principe",
    displayName: "São Tomé & Príncipe",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "2800 / 1400",
    bands: [
      { label: "green field", hex: "#12AD2B" },
    ],
  },
  {
    code: "SV",
    id: "el-salvador",
    slug: "el-salvador",
    displayName: "El Salvador",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "1005 / 567",
    bands: [
      { label: "blue field", hex: "#0047AB" },
    ],
  },
  {
    code: "SY",
    id: "syria",
    slug: "syria",
    displayName: "Syria",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "900 / 600",
    bands: [
      { label: "green field", hex: "#007A3D" },
    ],
  },
  {
    code: "SZ",
    id: "eswatini",
    slug: "eswatini",
    displayName: "Eswatini",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "900 / 600",
    bands: [
      { label: "blue field", hex: "#3E5EB9" },
    ],
  },
  {
    code: "TD",
    id: "chad",
    slug: "chad",
    displayName: "Chad",
    region: "Africa",
    difficulty: "normal",
    aspectRatio: "3 / 2",
    bands: [
      { label: "red field", hex: "#C8102E" },
    ],
  },
  {
    code: "TG",
    id: "togo",
    slug: "togo",
    displayName: "Togo",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "809 / 500",
    bands: [
      { label: "green field", hex: "#006A4E" },
    ],
  },
  {
    code: "TH",
    id: "thailand",
    slug: "thailand",
    displayName: "Thailand",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "9 / 6",
    bands: [
      { label: "red field", hex: "#A51931" },
    ],
  },
  {
    code: "TJ",
    id: "tajikistan",
    slug: "tajikistan",
    displayName: "Tajikistan",
    region: "Asia",
    difficulty: "expert",
    aspectRatio: "1400 / 700",
    bands: [
      { label: "green field", hex: "#006600" },
    ],
  },
  {
    code: "TL",
    id: "timor-leste",
    slug: "timor-leste",
    displayName: "Timor-Leste",
    region: "Asia",
    difficulty: "normal",
    aspectRatio: "1200 / 600",
    bands: [
      { label: "red field", hex: "#DC241F" },
    ],
  },
  {
    code: "TM",
    id: "turkmenistan",
    slug: "turkmenistan",
    displayName: "Turkmenistan",
    region: "Asia",
    difficulty: "expert",
    aspectRatio: "900 / 600",
    bands: [
      { label: "green field", hex: "#00843D" },
    ],
  },
  {
    code: "TN",
    id: "tunisia",
    slug: "tunisia",
    displayName: "Tunisia",
    region: "Africa",
    difficulty: "easy",
    aspectRatio: "120 / 80",
    bands: [
      { label: "red field", hex: "#E70013" },
    ],
  },
  {
    code: "TO",
    id: "tonga",
    slug: "tonga",
    displayName: "Tonga",
    region: "Oceania",
    difficulty: "easy",
    aspectRatio: "96 / 48",
    bands: [
      { label: "red field", hex: "#C10000" },
    ],
  },
  {
    code: "TR",
    id: "turkiye",
    slug: "turkiye",
    displayName: "Türkiye",
    region: "Asia",
    difficulty: "easy",
    aspectRatio: "12 / 8",
    bands: [
      { label: "red field", hex: "#E30A17" },
    ],
  },
  {
    code: "TT",
    id: "trinidad-and-tobago",
    slug: "trinidad-and-tobago",
    displayName: "Trinidad & Tobago",
    region: "Americas",
    difficulty: "easy",
    aspectRatio: "30 / 18",
    bands: [
      { label: "red field", hex: "#CE1126" },
    ],
  },
  {
    code: "TV",
    id: "tuvalu",
    slug: "tuvalu",
    displayName: "Tuvalu",
    region: "Oceania",
    difficulty: "expert",
    aspectRatio: "1200 / 600",
    bands: [
      { label: "blue field", hex: "#009CDE" },
    ],
  },
  {
    code: "TZ",
    id: "tanzania",
    slug: "tanzania",
    displayName: "Tanzania",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "72 / 48",
    bands: [
      { label: "blue field", hex: "#00A3DD" },
    ],
  },
  {
    code: "UA",
    id: "ukraine",
    slug: "ukraine",
    displayName: "Ukraine",
    region: "Europe",
    difficulty: "easy",
    aspectRatio: "3 / 2",
    bands: [
      { label: "blue field", hex: "#0057B7" },
    ],
  },
  {
    code: "UG",
    id: "uganda",
    slug: "uganda",
    displayName: "Uganda",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "900 / 600",
    bands: [
      { label: "red field", hex: "#D90000" },
    ],
  },
  {
    code: "US",
    id: "united-states",
    slug: "united-states",
    displayName: "United States",
    region: "Americas",
    difficulty: "normal",
    aspectRatio: "7410 / 3900",
    bands: [
      { label: "red field", hex: "#B22234" },
    ],
  },
  {
    code: "UY",
    id: "uruguay",
    slug: "uruguay",
    displayName: "Uruguay",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "945 / 630",
    bands: [
      { label: "blue field", hex: "#0038A8" },
    ],
  },
  {
    code: "UZ",
    id: "uzbekistan",
    slug: "uzbekistan",
    displayName: "Uzbekistan",
    region: "Asia",
    difficulty: "expert",
    aspectRatio: "500 / 250",
    bands: [
      { label: "green field", hex: "#1EB53A" },
    ],
  },
  {
    code: "VA",
    id: "vatican-city",
    slug: "vatican-city",
    displayName: "Vatican City",
    region: "Europe",
    difficulty: "expert",
    aspectRatio: "2500 / 2500",
    bands: [
      { label: "yellow field", hex: "#FFE000" },
    ],
  },
  {
    code: "VC",
    id: "st-vincent-and-grenadines",
    slug: "st-vincent-and-grenadines",
    displayName: "St. Vincent & Grenadines",
    region: "Americas",
    difficulty: "normal",
    aspectRatio: "192 / 128",
    bands: [
      { label: "yellow field", hex: "#FCD022" },
    ],
  },
  {
    code: "VE",
    id: "venezuela",
    slug: "venezuela",
    displayName: "Venezuela",
    region: "Americas",
    difficulty: "expert",
    aspectRatio: "180 / 120",
    bands: [
      { label: "red field", hex: "#CF142B" },
    ],
  },
  {
    code: "VN",
    id: "vietnam",
    slug: "vietnam",
    displayName: "Vietnam",
    region: "Asia",
    difficulty: "easy",
    aspectRatio: "30 / 20",
    bands: [
      { label: "red field", hex: "#DA251D" },
    ],
  },
  {
    code: "VU",
    id: "vanuatu",
    slug: "vanuatu",
    displayName: "Vanuatu",
    region: "Oceania",
    difficulty: "normal",
    aspectRatio: "950 / 570",
    bands: [
      { label: "green field", hex: "#009543" },
    ],
  },
  {
    code: "WS",
    id: "samoa",
    slug: "samoa",
    displayName: "Samoa",
    region: "Oceania",
    difficulty: "normal",
    aspectRatio: "2880 / 1440",
    bands: [
      { label: "red field", hex: "#CE1126" },
    ],
  },
  {
    code: "YE",
    id: "yemen",
    slug: "yemen",
    displayName: "Yemen",
    region: "Asia",
    difficulty: "easy",
    aspectRatio: "9 / 6",
    bands: [
      { label: "red field", hex: "#CE1126" },
    ],
  },
  {
    code: "ZA",
    id: "south-africa",
    slug: "south-africa",
    displayName: "South Africa",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "9 / 6",
    bands: [
      { label: "blue field", hex: "#001489" },
    ],
  },
  {
    code: "ZM",
    id: "zambia",
    slug: "zambia",
    displayName: "Zambia",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "2100 / 1400",
    bands: [
      { label: "green field", hex: "#198A00" },
    ],
  },
  {
    code: "ZW",
    id: "zimbabwe",
    slug: "zimbabwe",
    displayName: "Zimbabwe",
    region: "Africa",
    difficulty: "expert",
    aspectRatio: "1260 / 630",
    bands: [
      { label: "green field", hex: "#006400" },
    ],
  },
];

export const worldFlagsPack: ContentPack = {
  id: "world-flags",
  name: "World Flags",
  version: "1.0.0",
  license: "Public Domain (upstream declaration)",
  sourceUrl: "https://github.com/hampusborgos/country-flags",
  targets: flagDefinitions.flatMap((flag) => flag.bands.map((item) => ({
    id: `world-flags-${flag.id}-${bandKey(item.label)}`,
    prompt: `Remember the ${item.label} in the flag of ${flag.displayName}`,
    difficulty: flag.difficulty,
    targetHex: item.hex as `#${string}`,
    visual: { kind: "image" as const, imageSrc: `/content/flags/${flag.code.toLowerCase()}.svg` },
  }))),
};
